<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Krosoft.Extensions.Testing" Version="2026.9.5.10275" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\src\Krosoft.Extensions.Hosting\Krosoft.Extensions.Hosting.csproj" />
	</ItemGroup>
	<ItemGroup>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>